# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2017-08-05 13:25:37 +0100 by conor:
gem "cocoapods", "~> 1.3"
